flags: {}
packages:
    - '.'
extra-deps:
    - helm-0.7.1
    - elerea-2.8.0
    - cairo-0.12.5.3
    - utf8-string-0.3.8
    - pango-0.12.5.3
    - sdl2-1.2.0
    - glib-0.12.5.4
    - AC-Vector-1.2.2
    - basic-prelude-0.4.0
    - classy-prelude-0.12.1.1
resolver: lts-2.14
